### ISSUE TITLE
The bug of main.py

### ISSUE THREAD

**Issue by wuyifujia** [fredzzhang/spatio-attentive-graphs#36]
Dear Professor , excuse me.  I have a problem that I want to get a solution from you. when I run main.py, it has a problem as follows.
![image](https://user-images.githubusercontent.com/75160265/106918090-db05eb00-6743-11eb-8b47-f746952781b3.png)

And I have followed your guide step by step, but it still can not run rightly, I am very grateful to you if you give me a solution when you have time. Thank you very much!

**Comment by fredzzhang** [comment]
Hi, @wuyifujia 

I'm no professor :) The problem you had was caused by incorrect version of `torchvision`. I think you installed PyTorch 1.7 with Torchvision 0.8. Following the prerequisite I listed below, make sure to get the correct version of Pocket and PyTorch
```
2. Install the lightweight deep learning library Pocket (use release v0.3 with PyTorch 1.1.0)
```

Let me know if that doesn't solve the problem.

Cheers,
Fred

**Comment by fredzzhang** [comment]
I've updated the code base to support PyTorch 1.7.1 and torchvision 0.8 in #37. Ignore my last comment and simply pull from the main branch. This should solve the problem.

Cheers,
Fred

**Comment by wuyifujia** [comment]
dear sir, I have pull the latest code from the main branch again, but there is  still a problem that I need to sovle after I try to run main.py. I have set num_workers=0 ,but this still des not work. I want to ask if I need do something to deal with this package?
![image](https://user-images.githubusercontent.com/75160265/107051033-ea9a3800-6806-11eb-94ae-39a9b1f5ea24.png)
![image](https://user-images.githubusercontent.com/75160265/107051504-8035c780-6807-11eb-9034-3ada48b1d850.png)

I am looking forward to your reply, Thank you very much!

**Comment by wuyifujia** [comment]
And could you please vertify the code that will fit pytorch=1.6.0? :)

Best wishes!

**Comment by wuyifujia** [comment]
And I find the package I drew in the picture is already exist.

**Comment by fredzzhang** [comment]
Hi, @wuyifujia 

The error you have is related to caffe2, which has nothing to do with this repo. I suggest you start over with a clean conda environment and re-install all the dependencies following the instructions.

Fred

**Comment by wuyifujia** [comment]
OK, thank you. I will take a try!

Best wishes!

**Comment by wuyifujia** [comment]
dear sir, I have created a new environment and installed pytorch==1.7.1 again,  but there is still a problem as before, and I have set num_workers=0 and batch_size=1, but it did not make use.
![image](https://user-images.githubusercontent.com/75160265/107113107-c0dd2180-6897-11eb-9d4a-22576b6586d5.png)
![image](https://user-images.githubusercontent.com/75160265/107117754-6e136200-68b7-11eb-9d93-3059f494bab0.png)

Could you please give me some advice? Thank you very much!

**Comment by fredzzhang** [comment]
Well...the error shows that you are out of RAM. Did you attempt to train it with CPU?

**Comment by wuyifujia** [comment]
I have commented the lines in main.py as follows :
![image](https://user-images.githubusercontent.com/75160265/107135757-4b755d80-6938-11eb-8f2e-bc6c39e8e759.png)
There is still an error after training as before,  if the memory of RAM really has some proeblems, the proecess maybe will not start, but it start training after I run main.py. When it has finished the task, there was an error as follows, which is the same as the result when I train it with GPU.
![image](https://user-images.githubusercontent.com/75160265/107135514-60e98800-6936-11eb-93c6-7ab2dcdbd25c.png)
![image](https://user-images.githubusercontent.com/75160265/107136770-14f01080-6941-11eb-8a33-e6446abff168.png)

**Comment by fredzzhang** [comment]
Hi, @wuyifujia 

The two lines of code you commented out normally wouldn't make any difference. Did you run the program by specifying `CUDA_VISIBLE_DEVICES`?

Since you are able to run the script and train for almost half of an epoch, at least that shows the environment is correctly set up. I don't know why the program is running out of RAM half way through. The `RuntimeError` itself is too ambiguous. I need you to paste the entire error message to find out where the problem might originate.

Fred

**Comment by wuyifujia** [comment]
Yes, I also think it is too ambiguous:)
It  has almost finished all the training task(36000/37633) when the program is running out of RAM, and I have checked the load of CPU and GPU all the time, which is almost 45% and 56% respectively. So I think the memory of GPU or CPU is not overloaded. I have put the entire error for you as follows:
![image](https://user-images.githubusercontent.com/75160265/107141151-ea627f80-6961-11eb-8411-d98c72a2f114.png)
![image](https://user-images.githubusercontent.com/75160265/107141629-fdc31a00-6964-11eb-9e69-781d1de8b789.png)
![image](https://user-images.githubusercontent.com/75160265/107141633-0ca9cc80-6965-11eb-80b8-2b999e0d2278.png)
![image](https://user-images.githubusercontent.com/75160265/107141636-18958e80-6965-11eb-9a52-baa7b6a0e709.png)

**Comment by fredzzhang** [comment]
OK. This is a lot clearer now. The training was running perfectly, and so was the validation. The problem is in the mAP evaluation it seems. By default, the number of processes used for mAP evaluation is 20. That might have consumed more memory than you have.

Since you are using a single GPU for training, go to `utils.py`. At line 204 and 244, add argument `nproc=1` when instantiating `DetectionAPMeter`. This will disable the multiprocessing.

Give this a try and see if you still have the error.

**Comment by wuyifujia** [comment]
It's OK! I have solved the problems above. Thanks for your patient answer, and I am grateful for you to help me deal with errors.
Wish you will have an infinitely bright future! Sincerely thanks again！

Best wishes!

**Comment by fredzzhang** [comment]
Good to know it's working. But note that smaller batch sizes might result in inferior performance. Closing this now.
